on:
  push:
    branches:
      - master
      
name: Higher Vibe Healing Deploy

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Serverless Push
      id: serverless-push
      env:
        AWS_EC2_METADATA_DISABLED: true
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 rm s3://highervibehealing.com --recursive
        aws s3 sync . s3://highervibehealing.com --exclude '.git/*' --exclude '.github/*' --exclude 'README.md' --acl public-read
    - name: Tag Build Back To GitHub
      id: tag-build
      env:
        BRANCH: ${{ github.ref }}
      run: |
        NEWTAG=${BRANCH##*/}-$(date +%Y%m%d-%H%M%S)
        git tag $NEWTAG
        git push origin $NEWTAG